// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3d48P3y5IR_P-RBL2o5KsxS3uujGn_w',
    appId: '1:542805864316:web:b1324a8502245601f23ef9',
    messagingSenderId: '542805864316',
    projectId: 'unionshop-2b74d',
    authDomain: 'unionshop-2b74d.firebaseapp.com',
    storageBucket: 'unionshop-2b74d.firebasestorage.app',
    measurementId: 'G-3GWML4YMGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUEm5_oqjb3uQW07Qg3B2xeP_27zAwAZY',
    appId: '1:542805864316:android:061d91ee3f6c9166f23ef9',
    messagingSenderId: '542805864316',
    projectId: 'unionshop-2b74d',
    storageBucket: 'unionshop-2b74d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDctTNqkLD27rnXKugMosc1cn4SNZhTWY',
    appId: '1:542805864316:ios:ea315a8b196eb433f23ef9',
    messagingSenderId: '542805864316',
    projectId: 'unionshop-2b74d',
    storageBucket: 'unionshop-2b74d.firebasestorage.app',
    iosBundleId: 'com.example.unionShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3d48P3y5IR_P-RBL2o5KsxS3uujGn_w',
    appId: '1:542805864316:web:4ff17fe4706be79bf23ef9',
    messagingSenderId: '542805864316',
    projectId: 'unionshop-2b74d',
    authDomain: 'unionshop-2b74d.firebaseapp.com',
    storageBucket: 'unionshop-2b74d.firebasestorage.app',
    measurementId: 'G-CRSECVDSNQ',
  );
}
